import { HafalanCategory, SchoolConfig, Student } from '../types';

export const DEFAULT_SCHOOL_CONFIG: SchoolConfig = {
  schoolName: 'MADRASAH IBTIDAIYAH RAUDLATUL HIKMAH',
  title: 'LAPORAN KARTU HAFALAN SISWA',
  academicYear: '2026/2027',
  city: 'Tangerang Selatan',
  date: '16 Oktober 2026',
  examinerTitle: 'Guru Kelas / Penguji,',
  examinerName: 'FIKRA ABDILLAH ZAENAL, S.S, S.Pd',
  parentTitle: 'Orang Tua / Wali Murid,',
  parentName: '',
  customLogoUrl: null,
  examiners: [
    'q',
    'FIKRA ABDILLAH ZAENAL, S.S, S.Pd',
    'Ustadzah Rahmawati, S.Pd.I',
    'Ustadz Muhammad Ilham, Lc',
  ],
};

export const DEFAULT_CATEGORIES: HafalanCategory[] = [
  {
    id: 'cat_a',
    code: 'A',
    name: 'HAFALAN UMUM',
    targetClasses: ['Semua Kelas'],
    items: [
      { id: 'item_a_1', nama: 'Teks Pancasila dan simbolnya', targetClasses: ['Semua Kelas'] },
      { id: 'item_a_2', nama: 'Mars Madrasah', targetClasses: ['Semua Kelas'] },
    ],
  },
  {
    id: 'cat_b',
    code: 'B',
    name: 'DOA SEHARI-HARI',
    targetClasses: ['Semua Kelas'],
    items: [
      { id: 'item_b_1', nama: 'Doa Sebelum Makan', targetClasses: ['Semua Kelas'] },
      { id: 'item_b_2', nama: 'Doa Sesudah Makan', targetClasses: ['Semua Kelas'] },
      { id: 'item_b_3', nama: 'Doa Sebelum Tidur', targetClasses: ['Semua Kelas'] },
      { id: 'item_b_4', nama: 'Doa Bangun Tidur', targetClasses: ['Semua Kelas'] },
      { id: 'item_b_5', nama: 'Doa Masuk WC', targetClasses: ['2.1'] },
      { id: 'item_b_6', nama: 'Doa Keluar WC', targetClasses: ['2.1'] },
      { id: 'item_b_7', nama: 'Doa Memakai Pakaian', targetClasses: ['1.1'] },
    ],
  },
  {
    id: 'cat_c',
    code: 'C',
    name: 'BACAAN SHALAT',
    targetClasses: ['Semua Kelas'],
    items: [
      { id: 'item_c_1', nama: 'Bacaan Sujud', targetClasses: ['2.1'] },
      { id: 'item_c_2', nama: 'Bacaan Duduk Antara Dua Sujud', targetClasses: ['2.1'] },
      { id: 'item_c_3', nama: 'Bacaan Doa Iftitah', targetClasses: ['1.1'] },
    ],
  },
  {
    id: 'cat_d',
    code: 'D',
    name: 'SURAH PENDEK (JUZ AMMA)',
    targetClasses: ['Semua Kelas'],
    items: [
      { id: 'item_d_1', nama: 'Surat Al-Asr', targetClasses: ['2.1'] },
      { id: 'item_d_2', nama: 'Surat At-Takasur', targetClasses: ['2.1'] },
      { id: 'item_d_3', nama: "Surat Al-Qari'ah", targetClasses: ['2.1'] },
      { id: 'item_d_4', nama: 'Surat An-Nas & Al-Falaq', targetClasses: ['1.1'] },
      { id: 'item_d_5', nama: 'Surat Al-Ikhlas & Al-Lahab', targetClasses: ['1.1'] },
      { id: 'item_d_6', nama: 'Surat Al-Balad', targetClasses: ['3.1'] },
    ],
  },
  {
    id: 'cat_e',
    code: 'E',
    name: 'HADITS PILIHAN',
    targetClasses: ['Semua Kelas'],
    items: [
      { id: 'item_e_1', nama: 'Hadits Tentang Dilarang Marah', targetClasses: ['2.1'] },
      { id: 'item_e_2', nama: 'Hadits Tentang Kebersihan', targetClasses: ['Semua Kelas'] },
      { id: 'item_e_3', nama: 'Hadits Menuntut Ilmu', targetClasses: ['1.1'] },
    ],
  },
  {
    id: 'cat_f',
    code: 'F',
    name: 'HADITS PILIHAN',
    targetClasses: ['2.1'],
    items: [
      { id: 'item_f_1', nama: 'Ayat Kursi', targetClasses: ['2.1'] },
    ],
  },
];

export const DEFAULT_STUDENTS: Student[] = [
  {
    id: 'std_adia',
    name: 'ADIA PUTRI AZZAHRA',
    nis: '111236740052251026',
    nisn: '3183369703',
    kelas: '2.1',
    tahunPelajaran: '2026/2027',
    records: {
      item_a_1: { tanggal: '1', penguji: 'q', keterangan: 'Lulus' },
      item_a_2: { tanggal: '2', penguji: 'q', keterangan: 'Lulus' },
      item_b_1: { tanggal: '3', penguji: 'q', keterangan: 'Lulus' },
      item_b_2: { tanggal: '4', penguji: 'q', keterangan: 'Lulus' },
      item_b_3: { tanggal: '5', penguji: 'q', keterangan: 'Lulus' },
      item_b_4: { tanggal: '6', penguji: 'q', keterangan: 'Lulus' },
      item_b_5: { tanggal: '7', penguji: 'q', keterangan: 'Lulus' },
      item_b_6: { tanggal: '8', penguji: 'q', keterangan: 'Lulus' },
      item_c_1: { tanggal: '9', penguji: 'q', keterangan: 'Lulus' },
      item_c_2: { tanggal: '10', penguji: 'q', keterangan: 'Lulus' },
      item_d_1: { tanggal: '11', penguji: 'q', keterangan: 'Lulus' },
      item_d_2: { tanggal: '12', penguji: 'q', keterangan: 'Lulus' },
      item_d_3: { tanggal: '', penguji: '', keterangan: '' },
      item_e_1: { tanggal: '14', penguji: 'q', keterangan: 'Lulus' },
      item_e_2: { tanggal: '15', penguji: 'q', keterangan: 'Lulus' },
      item_f_1: { tanggal: '16', penguji: 'q', keterangan: 'Lulus' },
    },
  },
  {
    id: 'std_farhan',
    name: 'MUHAMMAD FARHAN HABIBIE',
    nis: '111236740052251027',
    nisn: '3183369704',
    kelas: '2.1',
    tahunPelajaran: '2026/2027',
    records: {
      item_a_1: { tanggal: '1', penguji: 'q', keterangan: 'Lulus' },
      item_a_2: { tanggal: '2', penguji: 'q', keterangan: 'Lulus' },
      item_b_1: { tanggal: '3', penguji: 'q', keterangan: 'Lulus' },
      item_b_2: { tanggal: '4', penguji: 'q', keterangan: 'Lulus' },
      item_b_3: { tanggal: '5', penguji: 'q', keterangan: 'Lulus' },
      item_b_4: { tanggal: '6', penguji: 'q', keterangan: 'Lulus' },
      item_b_5: { tanggal: '7', penguji: 'q', keterangan: 'Lulus' },
      item_b_6: { tanggal: '8', penguji: 'q', keterangan: 'Lulus' },
      item_c_1: { tanggal: '9', penguji: 'q', keterangan: 'Lulus' },
      item_c_2: { tanggal: '10', penguji: 'q', keterangan: 'Lulus' },
      item_d_1: { tanggal: '11', penguji: 'q', keterangan: 'Lulus' },
      item_d_2: { tanggal: '12', penguji: 'q', keterangan: 'Lulus' },
      item_d_3: { tanggal: '13', penguji: 'q', keterangan: 'Lulus' },
      item_e_1: { tanggal: '14', penguji: 'q', keterangan: 'Lulus' },
      item_e_2: { tanggal: '15', penguji: 'q', keterangan: 'Lulus' },
      item_f_1: { tanggal: '16', penguji: 'q', keterangan: 'Lulus' },
    },
  },
  {
    id: 'std_aisyah',
    name: 'AISYAH HUMAIRA AZZAHRA',
    nis: '111236740052251028',
    nisn: '3183369705',
    kelas: '2.1',
    tahunPelajaran: '2026/2027',
    records: {
      item_a_1: { tanggal: '1', penguji: 'q', keterangan: 'Lulus' },
      item_a_2: { tanggal: '2', penguji: 'q', keterangan: 'Lulus' },
      item_b_1: { tanggal: '3', penguji: 'q', keterangan: 'Lulus' },
      item_b_2: { tanggal: '4', penguji: 'q', keterangan: 'Lulus' },
      item_b_3: { tanggal: '', penguji: '', keterangan: '' },
      item_b_4: { tanggal: '', penguji: '', keterangan: '' },
      item_b_5: { tanggal: '', penguji: '', keterangan: '' },
      item_b_6: { tanggal: '', penguji: '', keterangan: '' },
      item_c_1: { tanggal: '', penguji: '', keterangan: '' },
      item_c_2: { tanggal: '', penguji: '', keterangan: '' },
      item_d_1: { tanggal: '', penguji: '', keterangan: '' },
      item_d_2: { tanggal: '', penguji: '', keterangan: '' },
      item_d_3: { tanggal: '', penguji: '', keterangan: '' },
      item_e_1: { tanggal: '', penguji: '', keterangan: '' },
      item_e_2: { tanggal: '', penguji: '', keterangan: '' },
      item_f_1: { tanggal: '', penguji: '', keterangan: '' },
    },
  },
  {
    id: 'std_rayyan',
    name: 'AHMAD RAYYAN AL-FATIH',
    nis: '111236740052251029',
    nisn: '3183369706',
    kelas: '1.1',
    tahunPelajaran: '2026/2027',
    records: {
      item_a_1: { tanggal: '1', penguji: 'q', keterangan: 'Lulus' },
      item_a_2: { tanggal: '2', penguji: 'q', keterangan: 'Lulus' },
      item_b_1: { tanggal: '3', penguji: 'q', keterangan: 'Lulus' },
      item_b_2: { tanggal: '4', penguji: 'q', keterangan: 'Lulus' },
      item_b_7: { tanggal: '5', penguji: 'q', keterangan: 'Lulus' },
      item_c_3: { tanggal: '6', penguji: 'q', keterangan: 'Lulus' },
      item_d_4: { tanggal: '7', penguji: 'q', keterangan: 'Lulus' },
      item_d_5: { tanggal: '8', penguji: 'q', keterangan: 'Lulus' },
      item_e_3: { tanggal: '9', penguji: 'q', keterangan: 'Lulus' },
    },
  },
  {
    id: 'std_fatimah',
    name: 'FATIMAH AZ-ZAHRA',
    nis: '111236740052251030',
    nisn: '3183369707',
    kelas: '5',
    tahunPelajaran: '2026/2027',
    records: {
      item_a_1: { tanggal: '1', penguji: 'q', keterangan: 'Lulus' },
      item_a_2: { tanggal: '2', penguji: 'q', keterangan: 'Lulus' },
      item_b_1: { tanggal: '3', penguji: 'q', keterangan: 'Lulus' },
      item_b_2: { tanggal: '4', penguji: 'q', keterangan: 'Lulus' },
      item_c_1: { tanggal: '5', penguji: 'q', keterangan: 'Lulus' },
      item_d_1: { tanggal: '6', penguji: 'q', keterangan: 'Lulus' },
      item_e_2: { tanggal: '7', penguji: 'q', keterangan: 'Lulus' },
    },
  },
];
