import { HafalanCategory, SchoolConfig, Student } from '../types';

export const DEFAULT_SCHOOL_CONFIG: SchoolConfig = {
  schoolName: 'MADRASAH IBTIDAIYAH RAUDLATUL HIKMAH',
  title: 'LAPORAN KARTU HAFALAN SISWA',
  academicYear: '2026/2027',
  city: 'Tangerang Selatan',
  date: '16 Oktober 2026',
  examinerTitle: 'Guru Kelas / Penguji,',
  examinerName: 'FIKRA ABDILLAH ZAENAL, S.S, S.Pd',
  parentTitle: 'Orang Tua / Wali Murid,',
  parentName: '',
  customLogoUrl: null,
};

export const DEFAULT_CATEGORIES: HafalanCategory[] = [
  {
    id: 'cat_a',
    code: 'A',
    name: 'HAFALAN UMUM',
    items: [
      { id: 'item_a_1', nama: 'Teks Pancasila dan simbolnya' },
      { id: 'item_a_2', nama: 'Mars Madrasah' },
    ],
  },
  {
    id: 'cat_b',
    code: 'B',
    name: 'DOA SEHARI-HARI',
    items: [
      { id: 'item_b_1', nama: 'Doa Sebelum Makan' },
      { id: 'item_b_2', nama: 'Doa Sesudah Makan' },
      { id: 'item_b_3', nama: 'Doa Sebelum Tidur' },
      { id: 'item_b_4', nama: 'Doa Bangun Tidur' },
      { id: 'item_b_5', nama: 'Doa Masuk WC' },
      { id: 'item_b_6', nama: 'Doa Keluar WC' },
    ],
  },
  {
    id: 'cat_c',
    code: 'C',
    name: 'BACAAN SHALAT',
    items: [
      { id: 'item_c_1', nama: 'Bacaan Sujud' },
      { id: 'item_c_2', nama: 'Bacaan Duduk Antara Dua Sujud' },
    ],
  },
  {
    id: 'cat_d',
    code: 'D',
    name: 'SURAH PENDEK (JUZ AMMA)',
    items: [
      { id: 'item_d_1', nama: 'Surat Al-Asr' },
      { id: 'item_d_2', nama: 'Surat At-Takasur' },
      { id: 'item_d_3', nama: "Surat Al-Qari'ah" },
    ],
  },
  {
    id: 'cat_e',
    code: 'E',
    name: 'HADITS PILIHAN',
    items: [
      { id: 'item_e_1', nama: 'Hadits Tentang Dilarang Marah' },
      { id: 'item_e_2', nama: 'Hadits Tentang Kebersihan' },
    ],
  },
  {
    id: 'cat_f',
    code: 'F',
    name: 'HADITS PILIHAN', // In the original document, section F is labeled HADITS PILIHAN with Ayat Kursi
    items: [
      { id: 'item_f_1', nama: 'Ayat Kursi' },
    ],
  },
];

export const DEFAULT_STUDENTS: Student[] = [
  {
    id: 'std_adia',
    name: 'ADIA PUTRI AZZAHRA',
    nis: '111236740052251026',
    nisn: '3183369703',
    kelas: '2.1',
    tahunPelajaran: '2026/2027',
    records: {
      item_a_1: { tanggal: '1', penguji: 'q', keterangan: 'Lulus' },
      item_a_2: { tanggal: '2', penguji: 'q', keterangan: 'Lulus' },
      item_b_1: { tanggal: '3', penguji: 'q', keterangan: 'Lulus' },
      item_b_2: { tanggal: '4', penguji: 'q', keterangan: 'Lulus' },
      item_b_3: { tanggal: '5', penguji: 'q', keterangan: 'Lulus' },
      item_b_4: { tanggal: '6', penguji: 'q', keterangan: 'Lulus' },
      item_b_5: { tanggal: '7', penguji: 'q', keterangan: 'Lulus' },
      item_b_6: { tanggal: '8', penguji: 'q', keterangan: 'Lulus' },
      item_c_1: { tanggal: '9', penguji: 'q', keterangan: 'Lulus' },
      item_c_2: { tanggal: '10', penguji: 'q', keterangan: 'Lulus' },
      item_d_1: { tanggal: '11', penguji: 'q', keterangan: 'Lulus' },
      item_d_2: { tanggal: '12', penguji: 'q', keterangan: 'Lulus' },
      item_d_3: { tanggal: '', penguji: '', keterangan: '' },
      item_e_1: { tanggal: '14', penguji: 'q', keterangan: 'Lulus' },
      item_e_2: { tanggal: '15', penguji: 'q', keterangan: 'Lulus' },
      item_f_1: { tanggal: '16', penguji: 'q', keterangan: 'Lulus' },
    },
  },
  {
    id: 'std_farhan',
    name: 'MUHAMMAD FARHAN HABIBIE',
    nis: '111236740052251027',
    nisn: '3183369704',
    kelas: '2.1',
    tahunPelajaran: '2026/2027',
    records: {
      item_a_1: { tanggal: '1', penguji: 'q', keterangan: 'Lulus' },
      item_a_2: { tanggal: '2', penguji: 'q', keterangan: 'Lulus' },
      item_b_1: { tanggal: '3', penguji: 'q', keterangan: 'Lulus' },
      item_b_2: { tanggal: '4', penguji: 'q', keterangan: 'Lulus' },
      item_b_3: { tanggal: '5', penguji: 'q', keterangan: 'Lulus' },
      item_b_4: { tanggal: '6', penguji: 'q', keterangan: 'Lulus' },
      item_b_5: { tanggal: '7', penguji: 'q', keterangan: 'Lulus' },
      item_b_6: { tanggal: '8', penguji: 'q', keterangan: 'Lulus' },
      item_c_1: { tanggal: '9', penguji: 'q', keterangan: 'Lulus' },
      item_c_2: { tanggal: '10', penguji: 'q', keterangan: 'Lulus' },
      item_d_1: { tanggal: '11', penguji: 'q', keterangan: 'Lulus' },
      item_d_2: { tanggal: '12', penguji: 'q', keterangan: 'Lulus' },
      item_d_3: { tanggal: '13', penguji: 'q', keterangan: 'Lulus' },
      item_e_1: { tanggal: '14', penguji: 'q', keterangan: 'Lulus' },
      item_e_2: { tanggal: '15', penguji: 'q', keterangan: 'Lulus' },
      item_f_1: { tanggal: '16', penguji: 'q', keterangan: 'Lulus' },
    },
  },
  {
    id: 'std_aisyah',
    name: 'AISYAH HUMAIRA AZZAHRA',
    nis: '111236740052251028',
    nisn: '3183369705',
    kelas: '2.1',
    tahunPelajaran: '2026/2027',
    records: {
      item_a_1: { tanggal: '1', penguji: 'q', keterangan: 'Lulus' },
      item_a_2: { tanggal: '2', penguji: 'q', keterangan: 'Lulus' },
      item_b_1: { tanggal: '3', penguji: 'q', keterangan: 'Lulus' },
      item_b_2: { tanggal: '4', penguji: 'q', keterangan: 'Lulus' },
      item_b_3: { tanggal: '', penguji: '', keterangan: '' },
      item_b_4: { tanggal: '', penguji: '', keterangan: '' },
      item_b_5: { tanggal: '', penguji: '', keterangan: '' },
      item_b_6: { tanggal: '', penguji: '', keterangan: '' },
      item_c_1: { tanggal: '', penguji: '', keterangan: '' },
      item_c_2: { tanggal: '', penguji: '', keterangan: '' },
      item_d_1: { tanggal: '', penguji: '', keterangan: '' },
      item_d_2: { tanggal: '', penguji: '', keterangan: '' },
      item_d_3: { tanggal: '', penguji: '', keterangan: '' },
      item_e_1: { tanggal: '', penguji: '', keterangan: '' },
      item_e_2: { tanggal: '', penguji: '', keterangan: '' },
      item_f_1: { tanggal: '', penguji: '', keterangan: '' },
    },
  },
];
